swagger: "2.0"
info:
  title: "Pixel Canvas API"
  description: "API Gateway for serverless pixel canvas application"
  version: "2.0.0"
schemes:
  - "https"
produces:
  - "application/json"
paths:
  /discord/webhook:
    post:
      summary: "Discord webhook endpoint"
      operationId: "discordWebhook"
      x-google-backend:
        address: "${discord_proxy_url}"
        protocol: "h2"
      responses:
        200:
          description: "Success"
        401:
          description: "Unauthorized"
        500:
          description: "Internal server error"

  /auth/login:
    get:
      summary: "Initiate Discord OAuth2 login"
      operationId: "authLogin"
      x-google-backend:
        address: "${auth_handler_url}"
        protocol: "h2"
      responses:
        302:
          description: "Redirect to Discord OAuth2"
        500:
          description: "Internal server error"

  /auth/callback:
    get:
      summary: "Discord OAuth2 callback"
      operationId: "authCallback"
      x-google-backend:
        address: "${auth_handler_url}"
        protocol: "h2"
      parameters:
        - in: query
          name: code
          type: string
          required: true
          description: "OAuth2 authorization code"
        - in: query
          name: state
          type: string
          description: "OAuth2 state parameter"
      responses:
        200:
          description: "Authentication successful, returns JWT"
        401:
          description: "Authentication failed"
        500:
          description: "Internal server error"
