swagger: "2.0"
info:
  title: "Pixel Canvas API"
  description: "API Gateway for serverless pixel canvas application"
  version: "2.0.0"
schemes:
  - "https"
produces:
  - "application/json"
paths:
  /discord/webhook:
    post:
      summary: "Discord webhook endpoint"
      operationId: "discordWebhook"
      x-google-backend:
        address: "${discord_proxy_url}"
        protocol: "h2"
      responses:
        200:
          description: "Success"
        401:
          description: "Unauthorized"
        500:
          description: "Internal server error"
