swagger: "2.0"
info:
  title: "Pixel Canvas API"
  description: "API Gateway for serverless pixel canvas application"
  version: "1.0.0"
schemes:
  - "https"
produces:
  - "application/json"
paths:
  /discord/webhook:
    post:
      summary: "Discord webhook endpoint"
      operationId: "discordWebhook"
      x-google-backend:
        address: "${discord_proxy_url}"
        protocol: "h2"
      responses:
        200:
          description: "Success"
        401:
          description: "Unauthorized"
        500:
          description: "Internal server error"

  /api/pixels:
    post:
      summary: "Place a pixel on the canvas"
      operationId: "placePixel"
      x-google-backend:
        address: "${web_proxy_url}"
        protocol: "h2"
      parameters:
        - in: header
          name: Authorization
          type: string
          required: true
          description: "Bearer token"
      responses:
        200:
          description: "Pixel placed successfully"
        401:
          description: "Unauthorized"
        429:
          description: "Rate limit exceeded"
        500:
          description: "Internal server error"

    get:
      summary: "Get all pixels or pixels in a region"
      operationId: "getPixels"
      x-google-backend:
        address: "${web_proxy_url}"
        protocol: "h2"
      parameters:
        - in: query
          name: x1
          type: integer
          description: "Starting x coordinate"
        - in: query
          name: y1
          type: integer
          description: "Starting y coordinate"
        - in: query
          name: x2
          type: integer
          description: "Ending x coordinate"
        - in: query
          name: y2
          type: integer
          description: "Ending y coordinate"
      responses:
        200:
          description: "Pixels retrieved successfully"
        500:
          description: "Internal server error"

  /api/canvas:
    get:
      summary: "Get canvas state and metadata"
      operationId: "getCanvas"
      x-google-backend:
        address: "${web_proxy_url}"
        protocol: "h2"
      responses:
        200:
          description: "Canvas state retrieved successfully"
        500:
          description: "Internal server error"

  /auth/login:
    get:
      summary: "Initiate Discord OAuth2 login"
      operationId: "authLogin"
      x-google-backend:
        address: "${auth_handler_url}"
        protocol: "h2"
      responses:
        302:
          description: "Redirect to Discord OAuth2"
        500:
          description: "Internal server error"

  /auth/callback:
    get:
      summary: "Discord OAuth2 callback"
      operationId: "authCallback"
      x-google-backend:
        address: "${auth_handler_url}"
        protocol: "h2"
      parameters:
        - in: query
          name: code
          type: string
          required: true
          description: "OAuth2 authorization code"
        - in: query
          name: state
          type: string
          description: "OAuth2 state parameter"
      responses:
        200:
          description: "Authentication successful, returns JWT"
        401:
          description: "Authentication failed"
        500:
          description: "Internal server error"

  /auth/me:
    get:
      summary: "Get current user info"
      operationId: "authMe"
      x-google-backend:
        address: "${auth_handler_url}"
        protocol: "h2"
      parameters:
        - in: header
          name: Authorization
          type: string
          required: true
          description: "Bearer token"
      responses:
        200:
          description: "User info retrieved successfully"
        401:
          description: "Unauthorized"
        500:
          description: "Internal server error"
